name: push_release_nuget

# on push on master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@main
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Publish VL Nuget
      uses: vvvv/PublishVLNuget@1.0.42
      with:
        csproj: src\VL.Addons.sln
        nuspec: deployment\VL.Addons.nuspec
        icon-src: https://raw.githubusercontent.com/bj-rn/VL.Addons/master/resources/icon.png
        icon-dst: ./deployment/icon.png
        nuget-key: ${{ secrets.NUGET_KEY }}